on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: calcit-lang/setup-calcit@704b3f5cd6f9ce3bd1e0c926dbdd1d181adb8180 # v1

      - name: Validate Calcit snapshot
        run: |
          caps --ci
          calcit calcit.cirru edit format
          git diff --exit-code -- calcit.cirru
          calcit calcit.cirru --check-only
          calcit calcit.cirru --entry run-tests --check-only
          calcit calcit.cirru --entry run-tests
          calcit calcit.cirru js
